/**
 * Plantilla de cursos estándar — secundaria peruana (CNEB)
 * La clave es el campo `orden` de la tabla grados (1=1ro … 5=5to)
 * NO usar IDs de BD porque cambian entre entornos.
 */
export const CURSOS_POR_GRADO: Record<number, string[]> = {
    1: [ // 1ro de Secundaria
        'Matemática',
        'Comunicación',
        'Inglés',
        'Historia, Geografía y Economía',
        'Formación Ciudadana y Cívica',
        'Persona, Familia y Relaciones Humanas',
        'Ciencia, Tecnología y Ambiente',
        'Educación para el Trabajo',
        'Educación Física',
        'Arte y Cultura',
        'Educación Religiosa',
    ],
    2: [ // 2do de Secundaria
        'Matemática',
        'Comunicación',
        'Inglés',
        'Historia, Geografía y Economía',
        'Formación Ciudadana y Cívica',
        'Persona, Familia y Relaciones Humanas',
        'Ciencia, Tecnología y Ambiente',
        'Educación para el Trabajo',
        'Educación Física',
        'Arte y Cultura',
        'Educación Religiosa',
    ],
    3: [ // 3ro de Secundaria
        'Matemática',
        'Comunicación',
        'Inglés',
        'Historia, Geografía y Economía',
        'Formación Ciudadana y Cívica',
        'Persona, Familia y Relaciones Humanas',
        'Ciencia, Tecnología y Ambiente',
        'Educación para el Trabajo',
        'Educación Física',
        'Arte y Cultura',
        'Educación Religiosa',
    ],
    4: [ // 4to de Secundaria
        'Matemática',
        'Comunicación',
        'Inglés',
        'Historia, Geografía y Economía',
        'Formación Ciudadana y Cívica',
        'Persona, Familia y Relaciones Humanas',
        'Ciencia, Tecnología y Ambiente',
        'Educación para el Trabajo',
        'Educación Física',
        'Arte y Cultura',
        'Educación Religiosa',
    ],
    5: [ // 5to de Secundaria
        'Matemática',
        'Comunicación',
        'Inglés',
        'Historia, Geografía y Economía',
        'Formación Ciudadana y Cívica',
        'Persona, Familia y Relaciones Humanas',
        'Ciencia, Tecnología y Ambiente',
        'Educación para el Trabajo',
        'Educación Física',
        'Arte y Cultura',
        'Educación Religiosa',
    ],
};

export const COLORES_CURSOS: Record<string, string> = {
    'Matemática': '#3B82F6',
    'Comunicación': '#10B981',
    'Inglés': '#F59E0B',
    'Historia, Geografía y Economía': '#EF4444',
    'Formación Ciudadana y Cívica': '#8B5CF6',
    'Persona, Familia y Relaciones Humanas': '#EC4899',
    'Ciencia, Tecnología y Ambiente': '#06B6D4',
    'Educación para el Trabajo': '#F97316',
    'Educación Física': '#84CC16',
    'Arte y Cultura': '#A855F7',
    'Educación Religiosa': '#6B7280',
};